# Setup
title:               Taras Kloba
tagline:             'data engineering blog'
description:         'My name is Taras Kloba, and I am a Big Data Engineering Manager at SoftServe. I teach Software Engineers like you how to become a Data engineers.'
url:                 https://kloba.github.io
baseurl:             ""
paginate:            5
permalink:           '/:title'

# About/contact
author:
  name:              Taras Kloba
  url:               https://www.linkedin.com/in/kloba/
  email:             blog@klioba.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
