# Setup
title:               Taras Kloba
tagline:             'Taras Kloba'
description:         'Personal blog'
url:                 https://klioba.com
baseurl:             'https://kloba.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Taras Kloba
  url:               https://www.linkedin.com/in/kloba/
  email:             blog@klioba.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
